# Generated by Django 2.1.5 on 2021-01-22 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=150)),
                ('send_date', models.DateField()),
                ('menus_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menus.Menus')),
            ],
        ),
    ]
